### ISSUE TITLE
Linking against graphics libraries

### ISSUE THREAD

**Issue by andrey-popov** [JHUGen/JHUGenMELA#1]
This package links against ROOT libraries for event visualization. They are included [here](https://github.com/JHUGen/JHUGenMELA/blob/596da18cad09d00d30ff8ab3e1b3fdce81e83e33/MELA/makefile#L25). As a result, when an executable linked against `libJHUGenMELAMELA.so` starts, one gets a warning about DISPLAY not being set if running over SSH and not forwarding X11. To avoid this warning, the graphics libraries should not be used. It's enough to drop flag `--evelibs` at the line I referenced.

The same applies to the three subpackages in [`MelaAnalytics`](https://github.com/MELALabs/MelaAnalytics). There `root-config --glibs` should be replaced by `root-config --libs` in the makefiles.

**Comment by usarica** [comment]
@andrey-popov Thanks for pointing this out. I modified the makefile here and in MelaAnalytics to remove the graphics libraries as you suggested.
