### ISSUE TITLE
Debugging features that need to be implemented in the MELA Python wrapper

### ISSUE THREAD

**Issue by usarica** [JHUGen/JHUGenMELA#49]
Hi @MohitS704,

As mentioned during the LPC workshop tutorial, the Python wrapper needs to include debugging features. Specifically, we need to be able to call https://github.com/JHUGen/JHUGenMELA/blob/master/MELA/interface/TUtil.hh#L332-L333.

Would you mind submitting a PR to add a wrapper for these calls?

Thanks!

**Comment by usarica** [comment]
Please also kindly follow-up here and include a mention of this issue in the PR you create so that users of the Python wrapper can pick up the changes as soon as this debugging feature is introduced.

**Comment by MohitS704** [comment]
Working on this now. Should have a PR sometime soon.
